### ISSUE TITLE
Multiple allocated on CCC when user leave and join CCC space.

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#104]
When user leave CCC space and join the space again, they get additional 50CCC even though they might have receiver CCC before. 

As space admis, i want to ensure that user does not get multiple times CCC.

**Comment by KarimChabrak** [comment]
@pcP1r4t3    could you add a verification process here. 

VERIFY IF USER HAS ALTREADY AN ACCOUNT IN THE SPACE; IF YES the automatic coin allocation funtionality is not performed and thus no coins are allocated.

**Comment by pcP1r4t3** [comment]
OK  @KarimChabrak , I will implement that.

**Comment by gdalyy** [comment]
i'm working on this
