### ISSUE TITLE
Task module- display the coins allocated to the task

### ISSUE THREAD

**Issue by SeifBa** [Coinsence/meta#106]
The coins allocated to the task are not displayed in the task lists. 
![image](https://user-images.githubusercontent.com/46401803/60589621-3cace900-9d9a-11e9-934e-90080194699c.png)

![image](https://user-images.githubusercontent.com/46401803/60589665-564e3080-9d9a-11e9-8ec9-62f123f97a40.png)

**Comment by gdalyy** [comment]
Will do that , its important to see coins amount on the task overview.
 What do you think about allocating coins automatically through the task creation form ?

**Comment by SeifBa** [comment]
#107  ;)
