### ISSUE TITLE
Default account setting

### ISSUE THREAD

**Issue by SeifBa** [Coinsence/meta#109]
When the coins are sent to a user it requires a default account. I guess default account should automated.

**Comment by KarimChabrak** [comment]
agree with @SeifBa  .   We should maybe create for each user a single personal account and also hide the feature enabling user to create additional personal accounts.

**Comment by gdalyy** [comment]
@KarimChabrak I already solved that long time ago, users can't create personal accounts

**Comment by KarimChabrak** [comment]
@gdalyy true. The onlx point is that when making a trabnsaction and select user as owner, i need to select default, which does not make sense as there is only default account

**Comment by KarimChabrak** [comment]
@gdalyy i will close this issue then
