### ISSUE TITLE
Import wallet private key

### ISSUE THREAD

**Issue by haythem96** [Coinsence/meta#116]
The user should be able to import private key of any wallet belong to his account (platform account)

**Comment by gdalyy** [comment]
where to import the pk ?

**Comment by haythem96** [comment]
by import I mean just displaying the private key

**Comment by haythem96** [comment]
the private key is the content of `.key` file in the API so we need an endpoint to get the file content by the account guid.... for now this is not a priority, let if for month of September.

But just for contest, we can have like a button in front of each user account(wallet) when it get clicked, he need to confirm with the platform account password, if the password is correct then get the private key with http call and show it.
