### ISSUE TITLE
Reset task creates errors in accounting

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#119]
When resetting tasks, we get negative account balances.... 

When re-setting a task, nothing should be done with transaction.   As the transaction after closing the task is final.  

Only delete open task should move back coins from task account to original account where the coins come from.

![image](https://user-images.githubusercontent.com/41925899/64023805-66d01c80-cb39-11e9-9bab-f4c81197f85e.png)

**Comment by gdalyy** [comment]
I've removed the reset button.
