### ISSUE TITLE
Coin transaction did not work

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#128]
Was trying to transfer 0.200000048 project coins from my personal account to an other account (default space account). Somehow it did not work.

![image](https://user-images.githubusercontent.com/41925899/66800092-393a0980-ef14-11e9-931d-34dc43d7f121.png)

**Comment by gdalyy** [comment]
I think it's due to floating decimals. 
What did you decide ? should we keep working with integers or allow floats ?
