### ISSUE TITLE
Wrong notification when adding members to space

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#129]
I just accepted a space join request and got this message, even though this action was successfull and user is now space member. 

![image](https://user-images.githubusercontent.com/41925899/66804645-49a5b080-ef23-11e9-875c-0cc45a4d5d77.png)

**Comment by gdalyy** [comment]
I'll check it , but it seems to be that the user joined successfully the space humhub side, but there was an error on ethereum side
