### ISSUE TITLE
Change coin type and target amount in crowd funding campain

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#145]
When creating a crowd funding campain, I can not change selected coin type and target amount when i edit the campain. 

Maybe it is enougth, when user is able to delete the campain and start a new one.

**Comment by KarimChabrak** [comment]
sdsdsdfcds  ** dfd**  dfdf
dfdf d
dfdf  ### sdsd

**Comment by KarimChabrak** [comment]
sdsd **sdsd** sdsd sdsd

**Comment by KarimChabrak** [comment]
sds ### dfsdf ###

**Comment by gdalyy** [comment]
will have a look asap
