### ISSUE TITLE
Create page for public tasks

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#158]
Like crowdfunding and marketplaces, spaces shall be able to publish open tasks. 

The assets in the task account are showed.

**Comment by KarimChabrak** [comment]
One option is to create a marketplace for jobs, when user adds a job, he automatically generates a task. 

The marketplace card links directly to the task details.
The card which is similar to crowdfunding cars, shows a picture, task title, task description, task account balance and days left till the cheduled starting day of the task.

**Comment by KarimChabrak** [comment]
When creating a marketplace, add option "Task Marketplace"
![grafik](https://user-images.githubusercontent.com/41925899/100240569-02199280-2f33-11eb-84ba-1170e2bf62fc.png)

**Comment by KarimChabrak** [comment]
@gdalyy  check these potential changes

![Screenshot_20201202_184700_org mozilla firefox](https://user-images.githubusercontent.com/41925899/100913744-770c3f80-34d2-11eb-8803-81f5f4cb44dd.jpg)

**Comment by KarimChabrak** [comment]
![Screenshot_20201202_184803_org mozilla firefox](https://user-images.githubusercontent.com/41925899/100913765-7ecbe400-34d2-11eb-8f28-c7b0c929fa16.jpg)

**Comment by KarimChabrak** [comment]
![Screenshot_20201202_184838_org mozilla firefox](https://user-images.githubusercontent.com/41925899/100913807-8f7c5a00-34d2-11eb-816d-13e3ce64c6c1.jpg)

**Comment by KarimChabrak** [comment]
@gdalyy  please deploy this on menatabadol and Coinsence so that i can close it

**Comment by gdalyy** [comment]
I can't deploy on menatabadol I don't have access , @craxrev will you do it ?

@KarimChabrak I'll do deployment for coinsence for all branches all together one time ASAP.

**Comment by gdalyy** [comment]
Feel free to close the issue, it's not related to deployment :+1:
