### ISSUE TITLE
Change "cancel campaign"  and "accept investment" text and add option for re-start of campaign.

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#160]
I propose to make the buttons "cancel campaign"  and "accept investment" more accessible to user and not hide them under the "Edit" button.

See here

![image](https://user-images.githubusercontent.com/41925899/69190428-b151ab80-0b20-11ea-9ce5-a29e28a3a65b.png)

_Originally posted by @KarimChabrak in https://github.com/Coinsence/meta/issues/113#issuecomment-555736963_

**Comment by KarimChabrak** [comment]
Some User did click on Accept investmer by mistake when editing their campaign. 
![grafik](https://user-images.githubusercontent.com/41925899/78492527-31338780-7749-11ea-974f-544961b17dbc.png)


We need to change also text to: 
- "Close funding campaign and accept received COINs."
- "Cancel funding campaign and send back COINs."

We need also to add this text to the message list, to be able to translate to other languages.

**Comment by gdalyy** [comment]
:+1:

**Comment by KarimChabrak** [comment]
Based on latest experience when user click on "accept investment" by mistake. 

we need to break the old feature Accept investment in two steps ("Accept investment" and "Unpublish this campaign")
Here we keep campaign public when user clicks on accept investment. Add another button "Unpublish this campaign"

**Comment by KarimChabrak** [comment]
@gdalyy As many click by mistake "accept investment", we need the opposite button, when user click on "Close funding campaign and accept received COINs."

"Re-start this campaign"

Which makes campaign visible again abnd blocks accounts.

**Comment by gdalyy** [comment]
> @gdalyy As many click by mistake "accept investment", we need the opposite button, when user click on "Close funding campaign and accept received COINs."
> 
> "Re-start this campaign"
> 
> Which makes campaign visible again abnd blocks accounts.

I'm not understanding this well, can you explain further , what exactly should I do ?
