### ISSUE TITLE
Editing and approving funding campaign does not work

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#164]
Approving and disapproving campaign does not work. 

Editing campaign does not work, except when amount of requested coins is changed.

**Comment by KarimChabrak** [comment]
@gdalyy when you work on this, please also check if gallery pictures are also editable when after editing details, user clicks next

**Comment by gdalyy** [comment]
> @gdalyy when you work on this, please also check if gallery pictures are also editable when after editing details, user clicks next

Okay will check this
