### ISSUE TITLE
Message content display, when having multiple recipients

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#165]
This is how messages are shown, when having multiple recipients. It's not readable neither on mobile nor on desktop

![grafik](https://user-images.githubusercontent.com/41925899/84681367-4dffee80-af34-11ea-9eab-092224748428.png)

**Comment by KarimChabrak** [comment]
@craxrev I would be great if you could look at this.

**Comment by craxrev** [comment]
is this mail module related?

**Comment by KarimChabrak** [comment]
@craxrev yes, but it will be probably solved automatically with the new mail module.
