### ISSUE TITLE
Task error message

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#180]
When i create a task, set responsible user but do not set assigned user, I get a error message and cant open the task

e,g. https://dev.coinsence.org/tasktestingspace/tasks/task/view?id=47    I get error message 

- Potentially, only responsible user has this problem.
- To re-build this error:
- - Create task, set your self as responsible, do not set assigned user ----> you get error when you try to see the task
- - Edit task, add assigned person. ----> Error disappears

{
    "url": "/tasktestingspace/tasks/list/load-task-details?id=47",
    "status": 500,
    "response": "<pre>PHP Notice &#039;yii\\base\\ErrorException&#039; with message &#039;Undefined offset: 0&#039; \n\nin /var/www/coinsence_dev/protected/modules/tasks/widgets/ChooseWorkerAccountButton.php:25\n\nStack trace:\n#0 /var/www/coinsence_dev/protected/modules/tasks/widgets/ChooseWorkerAccountButton.php(25): yii\\base\\ErrorHandler-&gt;handleError(8, &#039;Undefined offse...&#039;, &#039;/var/www/coinse...&#039;, 25, Array)\n#1 /var/www/coinsence_dev/protected/humhub/components/Widget.php(58): humhub\\modules\\ta...",
    "textStatus": "error",
    "xhr": {
        "readyState": 4,
        "responseText": "<pre>PHP Notice &#039;yii\\base\\ErrorException&#039; with message &#039;Undefined offset: 0&#039; \n\nin /var/www/coinsence_dev/protected/modules/tasks/widgets/ChooseWorkerAccountButton.php:25\n\nStack trace:\n#0 /var/www/coinsence_dev/protected/modules/tasks/widgets/ChooseWorkerAccountButton.php(25): yii\\base\\ErrorHandler-&gt;handleError(8, &#039;Undefined offse...&#039;, &#039;/var/www/coinse...&#039;, 25, Array)\n#1 /var/www/coinsence_dev/protected/humhub/components/Widget.php(58): humhub\\modules\\tasks\\widgets\\ChooseWorkerAccountButton-&gt;run()\n#2 /var/www/coinsence_dev/protected/modules/tasks/widgets/lists/views/taskDetails.php(51): humhub\\components\\Widget::widget(Array)\n#3 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/base/View.php(336): require(&#039;/var/www/coinse...&#039;)\n#4 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/base/View.php(254): yii\\base\\View-&gt;renderPhpFile(&#039;/var/www/coinse...&#039;, Array)\n#5 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/base/View.php(156): yii\\base\\View-&gt;renderFile(&#039;/var/www/coinse...&#039;, Array, Object(humhub\\modules\\tasks\\widgets\\lists\\TaskListDetails))\n#6 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/base/Widget.php(236): yii\\base\\View-&gt;render(&#039;taskDetails&#039;, Array, Object(humhub\\modules\\tasks\\widgets\\lists\\TaskListDetails))\n#7 /var/www/coinsence_dev/protected/modules/tasks/widgets/lists/TaskListDetails.php(19): yii\\base\\Widget-&gt;render(&#039;taskDetails&#039;, Array)\n#8 /var/www/coinsence_dev/protected/humhub/components/Widget.php(58): humhub\\modules\\tasks\\widgets\\lists\\TaskListDetails-&gt;run()\n#9 /var/www/coinsence_dev/protected/modules/tasks/controllers/ListController.php(96): humhub\\components\\Widget::widget(Array)\n#10 [internal function]: humhub\\modules\\tasks\\controllers\\ListController-&gt;actionLoadTaskDetails(&#039;47&#039;)\n#11 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)\n#12 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\\base\\InlineAction-&gt;runWithParams(Array)\n#13 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\\base\\Controller-&gt;runAction(&#039;load-task-detai...&#039;, Array)\n#14 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\\base\\Module-&gt;runAction(&#039;tasks/list/load...&#039;, Array)\n#15 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\\web\\Application-&gt;handleRequest(Object(humhub\\components\\Request))\n#16 /var/www/coinsence_dev/index.php(27): yii\\base\\Application-&gt;run()\n#17 {main}</pre>",
        "status": 500,
        "statusText": "Internal Server Error"
    },
    "dataType": "html",
    "html": "<pre>PHP Notice &#039;yii\\base\\ErrorException&#039; with message &#039;Undefined offset: 0&#039; \n\nin /var/www/coinsence_dev/protected/modules/tasks/widgets/ChooseWorkerAccountButton.php:25\n\nStack trace:\n#0 /var/www/coinsence_dev/protected/modules/tasks/widgets/ChooseWorkerAccountButton.php(25): yii\\base\\ErrorHandler-&gt;handleError(8, &#039;Undefined offse...&#039;, &#039;/var/www/coinse...&#039;, 25, Array)\n#1 /var/www/coinsence_dev/protected/humhub/components/Widget.php(58): humhub\\modules\\ta...",
    "error": {},
    "errorThrown": "Internal Server Error",
    "validationError": false
}

**Comment by KarimChabrak** [comment]
@gdalyy   potentially, only responsible user has this problem.

**Comment by KarimChabrak** [comment]
To re-build this error.

Create task, set your self as responsible, do not set assigned user ---->  you get error when you try to see the task

Edit task, add assigned person.   ---->   Error disappears

**Comment by gdalyy** [comment]
Fixed in https://github.com/Coinsence/humhub-modules-tasks/pull/12
