### ISSUE TITLE
Beginning task

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#182]
User can beginn tasks which they are not allocated to. This is ok. 
We need to add the user who clicks on "Beginn Task" automatically to "assigned user".

**Comment by KarimChabrak** [comment]
This might solve also following error when i go through the process without assigning anybody.. 

{
    "url": "/testoptionaltask/tasks/task/proceed?id=81&status=5",
    "status": 500,
    "response": "<pre>Exception &#039;Error&#039; with message &#039;Call to a member function getAssets() on null&#039; \n\nin /var/www/coinsence_dev/protected/modules/tasks/models/Task.php:1178\n\nStack trace:\n#0 /var/www/coinsence_dev/protected/modules/tasks/controllers/TaskController.php(99): humhub\\modules\\tasks\\models\\Task-&gt;payWorker()\n#1 [internal function]: humhub\\modules\\tasks\\controllers\\TaskController-&gt;actionProceed(&#039;81&#039;, &#039;5&#039;)\n#2 /var/www/coinsence_dev/protected/vendor/yiisoft/yi...",
    "textStatus": "error",
    "xhr": {
        "readyState": 4,
        "responseText": "<pre>Exception &#039;Error&#039; with message &#039;Call to a member function getAssets() on null&#039; \n\nin /var/www/coinsence_dev/protected/modules/tasks/models/Task.php:1178\n\nStack trace:\n#0 /var/www/coinsence_dev/protected/modules/tasks/controllers/TaskController.php(99): humhub\\modules\\tasks\\models\\Task-&gt;payWorker()\n#1 [internal function]: humhub\\modules\\tasks\\controllers\\TaskController-&gt;actionProceed(&#039;81&#039;, &#039;5&#039;)\n#2 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)\n#3 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\\base\\InlineAction-&gt;runWithParams(Array)\n#4 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\\base\\Controller-&gt;runAction(&#039;proceed&#039;, Array)\n#5 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\\base\\Module-&gt;runAction(&#039;tasks/task/proc...&#039;, Array)\n#6 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\\web\\Application-&gt;handleRequest(Object(humhub\\components\\Request))\n#7 /var/www/coinsence_dev/index.php(27): yii\\base\\Application-&gt;run()\n#8 {main}</pre>",
        "status": 500,
        "statusText": "Internal Server Error"
    },
    "dataType": "html",
    "html": "<pre>Exception &#039;Error&#039; with message &#039;Call to a member function getAssets() on null&#039; \n\nin /var/www/coinsence_dev/protected/modules/tasks/models/Task.php:1178\n\nStack trace:\n#0 /var/www/coinsence_dev/protected/modules/tasks/controllers/TaskController.php(99): humhub\\modules\\tasks\\models\\Task-&gt;payWorker()\n#1 [internal function]: humhub\\modules\\tasks\\controllers\\TaskController-&gt;actionProceed(&#039;81&#039;, &#039;5&#039;)\n#2 /var/www/coinsence_dev/protected/vendor/yiisoft/yi...",
    "error": {},
    "errorThrown": "Internal Server Error",
    "validationError": false
}

**Comment by gdalyy** [comment]
resolved in https://github.com/Coinsence/humhub-modules-tasks/pull/14
