### ISSUE TITLE
Task issues when not creating account

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#189]
When I do not select to create an account,
- you get errors when closing task.
- Assigned person is still asked to choose payment account

**Comment by KarimChabrak** [comment]
@gdalyy one further issue

- If a do not select the create account in the beginn, I can not do it later, as the button does not appear when editing a task

**Comment by gdalyy** [comment]
resolved in https://github.com/Coinsence/humhub-modules-tasks/pull/13
