### ISSUE TITLE
Arabic Translation

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#192]
As we are targeting Arab region, I propose to translate main messages in Arabic.

We need a new extract of the messages, which i can translate

**Comment by gdalyy** [comment]
@craxrev :+1:

**Comment by craxrev** [comment]
I'll prepare the translation files some day in this week

**Comment by KarimChabrak** [comment]
**GENERALLY AND EVERYWHERE, NOT ARABIC NUMBER SHOULD BE USED, BUT THE STANDARD INTERNATIONAL NUMBERS**

**Profile page.** 
END Date not translated.
![grafik](https://user-images.githubusercontent.com/41925899/104822378-42fe9b00-5842-11eb-8f3b-797a10bbb41f.png)

**Tasks Missing following translations**
"Allocate coin  تخصيص عملة" and "create account إنشاء حساب"
![grafik](https://user-images.githubusercontent.com/41925899/104822490-27e05b00-5843-11eb-8e87-6b628662c301.png)

**In activity steam**
"Most active people الأعضاء الأكثر نشاطا" not translated
![grafik](https://user-images.githubusercontent.com/41925899/104329247-043cae00-54ed-11eb-96dc-995706a4de4f.png)

**In Space**
"Invite people دعوة الأعضاء" is not translated
![grafik](https://user-images.githubusercontent.com/41925899/104359677-3f9ca400-5510-11eb-9bd1-8896d781e2a5.png)
