### ISSUE TITLE
Re-design mail module

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#195]
I propose to implement the main module as shown here in the new design.

https://www.figma.com/file/7vafNwlSgNK2fCBzQ9TnvE/Coinsence---Redesign?node-id=0%3A1

@luke- If you are interested, we can try to create some synergies.

**Comment by luke-** [comment]
@KarimChabrak Have you already seen the new Mail Module (2.0) version?

**Comment by KarimChabrak** [comment]
@luke- I could not test it, because we are based on an old Humhub version and we need to invest quite some work to bring our version to the latest one.     It would be of course great if we can build on the new mail module. @craxrev started already.
Is there any access  where i can test the new mail module?

**Comment by luke-** [comment]
@KarimChabrak The easiest way is in our community or demo hosting.

**Comment by KarimChabrak** [comment]
Size of text and pictures is still to big, expecially comparing to other text and pictur icont in the platfrom (size should be e.g. like the ones highlighted in yellow in the the left side of the picture below). 
![grafik](https://user-images.githubusercontent.com/41925899/101806051-c9251480-3b13-11eb-83b2-9855a947ede7.png)

**Comment by KarimChabrak** [comment]
Also in the list of conversations, picture and text size should be as small as in the conversation details. 
![grafik](https://user-images.githubusercontent.com/41925899/101806389-2faa3280-3b14-11eb-9b20-f86f9c0ecf75.png)

**Comment by KarimChabrak** [comment]
@lemsadelavega  do you agree with the text size reduction in the conversation?

**Comment by luke-** [comment]
If you have improvements here, you are welcome to create a PR in our repo. Maybe with an issue for discussion before to avoid misconceptions.
