### ISSUE TITLE
User profile page

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#196]
Profile page shall be re-designed as shown here
https://www.figma.com/file/7vafNwlSgNK2fCBzQ9TnvE/Coinsence---Redesign

**Comment by KarimChabrak** [comment]
Following to be corrected
- Uploading button for profile picture is visible only curser is aside of picture. PROPOSAL: Make the buttons always visible for user (profile picture and background picture)
- I can not upload pictures, when selecting upload and then selecting a picture

**Comment by KarimChabrak** [comment]
Country list does not get loaded in experience
![grafik](https://user-images.githubusercontent.com/41925899/100375690-7bd27e80-300e-11eb-9504-2d3a7d27c061.png)

**Comment by KarimChabrak** [comment]
Coins on the rights side are not corrects

**Comment by KarimChabrak** [comment]
When adding experience, calendar function does not work. I propose to add in the comment the format to help user here YYYY-MM
![grafik](https://user-images.githubusercontent.com/41925899/100375903-d5d34400-300e-11eb-9def-a48fe3e50a93.png)

**Comment by KarimChabrak** [comment]
Reduce line distance within each experience
![grafik](https://user-images.githubusercontent.com/41925899/100376338-a6710700-300f-11eb-9e8e-e7a0ea854366.png)

**Comment by KarimChabrak** [comment]
I cant edit the text section here
![grafik](https://user-images.githubusercontent.com/41925899/100376404-be488b00-300f-11eb-9cd6-2990fe4b0a86.png)

**Comment by KarimChabrak** [comment]
We could reduce the space between "System admin..."  and the text below.

![grafik](https://user-images.githubusercontent.com/41925899/100376886-94dc2f00-3010-11eb-96f2-a4655bdcc959.png)

**Comment by KarimChabrak** [comment]
Let's hide this section for the moment, or replace it by this below from old profile view

![grafik](https://user-images.githubusercontent.com/41925899/100380472-38304280-3017-11eb-8949-29a588ee3747.png)

![grafik](https://user-images.githubusercontent.com/41925899/100380545-5d24b580-3017-11eb-85b9-c62e1a5ffd93.png)

**Comment by KarimChabrak** [comment]
RECENT POSTS should show only activites related to the user: 

![grafik](https://user-images.githubusercontent.com/41925899/100377560-c0134e00-3011-11eb-9460-1b74787f8d1d.png)

**Comment by KarimChabrak** [comment]
Clicking on "accounts" or on "account overview" does not lead to account overview. 

![grafik](https://user-images.githubusercontent.com/41925899/100378674-d3271d80-3013-11eb-931a-a76223d3135d.png)

![grafik](https://user-images.githubusercontent.com/41925899/100378754-0073cb80-3014-11eb-8b66-a3bbd83b85fd.png)

**Comment by KarimChabrak** [comment]
Missing instagramm
![grafik](https://user-images.githubusercontent.com/41925899/100379327-fd2d0f80-3014-11eb-9b3b-01a846e77488.png)

**Comment by craxrev** [comment]
@KarimChabrak don't think we have an instagram option it in user profile settings
