### ISSUE TITLE
Landing page for space

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#2]
As space administrator, I would like to share with new users and space members relevant information. User can learn about the goal of the space, the structure, link to relevant document, how to participate

For who, is this feature:
- new users that are visiting the space for the first time to learn about the space. this user has no idea about the space yet and wants to learn what is going on.
- existing space members, who are already active, but want to get new information about recent updates.
- only admins can edit the page

- landing page is shown to non-members
- members will see the stream but see a link to the landing page in the navigation

- admin has a simple form to fill in space introduction which is shown as landing page

ToDo:
- [x] provide example content

**Comment by KarimChabrak** [comment]
Space admin can already create pages

![image](https://user-images.githubusercontent.com/41925899/50842085-4fec7800-1366-11e9-915a-c2e283b2812d.png)

and also set which landig page shall be used for visitors and space members

![image](https://user-images.githubusercontent.com/41925899/50842246-90e48c80-1366-11e9-9551-e64532cfb591.png)

**Comment by gdalyy** [comment]
Karim, since most of parts of this issue is already solved by the feature of **custom pages** , can you describe further what should be also done ?

**Comment by KarimChabrak** [comment]
The current solution currently does not look good. All pictures are for example scaled over the full page.
Maybe this is more a frontend designer work.

**Comment by bumi** [comment]
will Salem look into this?

**Comment by KarimChabrak** [comment]
I think that it will need at least a month untill we get valuable feedback from product design side. Untill doing user research and joined design workshop, we have to work based on our own assumptions.

**Comment by bumi** [comment]
how do you come up with that number of a month? - let's discuss the process on slack?

**Comment by craxrev** [comment]
So, I'll be looking for any kind of enhancements, maybe there's a misuse or some kind of bad UI/UX?
Either ways, I'll make sure not touch any crucial parts in this feature as there's not fixed to-dos here.
In the meantime, **Karim** will discuss this with **Salem** hopefully not for a long time, otherwise, I'll be making a point with **Malek**, to further address this issue.

**Comment by gdalyy** [comment]
@craxrev, there's a new version for the  **custom pages** module ( Version : 0.8.10 -> Version : 0.8.11 ) , make sure you make the updates before starting.

**Comment by KarimChabrak** [comment]
@craxrev    Please let me know what feedback you need.

**Comment by craxrev** [comment]
Ok @KarimChabrak, this is what've got so far from this issue,

With the current module we have the following options for a user to add his custom page:
- Link: direct redirection to the set link, no view, no customization
- iframe: for lazy people, not an ergonomic view (the slider made it look bad), no customization
- MarkDown: easy to use for newbies, but lacks customization (limited by design)
- Templates: for advanced users, "fully" customizable (to an extent)

So a user can choose one of thoses options, but he shoudn't be surprised if he's chosen wrongly,
otherwise the task will be to add a fifth option which use a richtext implementation, I think the humhub core uses it, so maybe reimplemts it in this module, or maybe use a more robust feature like the one @gdalyy mentioned  [CKEditor](https://ckeditor.com/), so what do you think guys? @MalekTN also

**Comment by bumi** [comment]
as discussed in the call. 
@KarimChabrak describes some real-world content (for our project) that we would like to display on the landing page.
but technically we continue looking into the WYSIWYG editor and see if we can implement similarly as humhub already does.

**Comment by bumi** [comment]
oh and we need Salem's input on this

**Comment by craxrev** [comment]
Found an [issue](https://github.com/WASasquatch/humhub-modules-custom-pages-extended/issues/3) about the CKEditor implementation, talking about a bootstrap theme incompatibility. I'm testing it myself anyway.

**Comment by KarimChabrak** [comment]
This is below an example of content I would like to have on the space landing page. 
With the current solution, i can use MarkDown, but i can not control here the size of pictures and the position.   

![examplecontent](https://user-images.githubusercontent.com/41925899/52649807-4b792900-2ee9-11e9-8370-e1bd628867aa.JPG)

**Comment by bumi** [comment]
does the current solution actually support writing basic HTML? without a full editor? 
or can we simply support basic HTML in the landing page?

**Comment by bumi** [comment]
some other calculation:
If developing this feature costs us ~5days - we could spend 5 days to design landing pages for spaces.  I'd assume it takes less than half a day to design such a landing page, thus we could do it for up to 10 spaces and would still spend less time. 
how about we support basic HTML right now and offer spaces that we do it for them and see what they want?

**Comment by craxrev** [comment]
Yes, it does support adding basic HTML only through Templates, but it does not support adding a raw HTML page for security reasons (code injection) thus the limited usage of templates, but it's supported only for the space's admin in the module settings.
Found a discussion about this in a humhub repo [issue](https://github.com/humhub/humhub/issues/2203), and found another [one](https://github.com/humhub/humhub-modules-custom-pages/issues/52) discussing the option to add a setting to allow adding an html type page.

**Comment by bumi** [comment]
I don't fully get the security concern, as the WYISWG editor is also creating HTML, isn't it? 
The HTML should be sanitized and only support basic tags. 

do you know the code where the HTML is striped from the input?

**Comment by craxrev** [comment]
Yes we could limit the usage to only the basic tags, but I don't get the concern too, I don't know if there is any sanitisation process or not, I have to look into it tomorrow.
Another thing concerning the MarkDown option, there's a way to resize an image, I found a patch mentioned [here](https://github.com/humhub/humhub-modules-custom-pages/issues/63), it's not mainstreamed yet but I've tested it @KarimChabrak.

**Comment by craxrev** [comment]
What I've understood so far:
- templates are made only by the humhub administrators and they can choose whether they allow this layout to be selected in spaces or not.
- the space's admin can only change some sections of a chosen template, i.e. cannot add HTML tags, just writing text or uploading files for download.
- concerning the security issue, I found where the custom page content is processed <sup>[1](https://github.com/humhub/humhub-modules-custom-pages/blob/ec68f7cd32a42c6f4503db0dc3e568bac1485a6a/models/ContainerPage.php#L70)</sup>, it uses the **safe** validator to declare the attribute "page_content" as safe **without** validation <sup>[2](https://www.yiiframework.com/doc/guide/2.0/en/structure-models#safe-attributes)</sup>.
- as for sanitisation, it is used globally in text, upload, .. fields, but not in the HTML templates, I've tested against some xss attacks and I found that it's prone for such attacks but this is not critical as the HTML code of these templates is only managed by the humhub administrators, so he shoudn't do such things.

What I think we should do:

- Drop the option of the richtext implimentation as it is costly and complex.
- Strongly consider making fixed HTML templates to be used as standards for custom pages.
- Enhance the markdown editor experience, maybe add button/form for image size/pos.
- We should discuss througly the choice of giving the space's admin the ability to add his own HTML code, and whether it is **really** necessary for time being.

We should discuss this throughly in slack, or maybe we can make a demo on the template option, if it's not clear yet for any of you @KarimChabrak and @bumi.

**Comment by bumi** [comment]
what I still don't understand: how would the WYSIWYG like CKEditor work? the editor sill sends HTML to the server, doesn't it? So in order to support the editor we would somehow need to change the sanitization? 

with the markdown option we would also need to somewhere convert markdown into html? 

can't we use something like http://htmlpurifier.org/ to sanitize the input and then in the first step allow a certain set of HTML tags?

**Comment by bumi** [comment]
I think @KarimChabrak wants some certainty of customization so fixed templates is not an option?

**Comment by craxrev** [comment]
yes, to make the CKEditor valid, we should add the sanitization as there is no such process when sending the HTML to the server in the current case, we could consider using the builtin functions like `\yii\helpers\HtmlPurifier::process($description)`<sup>[1](https://www.yiiframework.com/doc/guide/2.0/en/security-best-practices)</sup>  and opt out of using external libs.

as for the markdown option, we could see in the [lib](https://github.com/humhub/humhub/blob/master/protected/humhub/libs/Markdown.php) code the heavy usage of regexs rules to render markdown into html, in this case markdown will be sent to server, sanitization here would be less of a problem.

anyway, I'll resume my work on the CKEditor integration and hopefully things get clearer.

**Comment by bumi** [comment]
ok, using those builtin functions sounds great. 
But then I'd propose we start with changing the backend to use those functions and allow space admins to use basic HTML. 
Once we have that everyone who knows HTML can already create nice landing pages (e.g. we can offer active spaces to build landing pages for them) 

On a later step we can extend that with a full CKEditor incl. file upload etc. 

what do you thinks?

**Comment by craxrev** [comment]
Yep, that would be a good first step, the code is already there (only available for humhub administrators), but needs some changes to add space admins also, though liked the idea of spaces for landing pages.

But I'll work on this for time being till we get everything sorted out (backend sensitization) then we'll build the full CKEditor.

**Comment by craxrev** [comment]
I've added the ability to add basic HTML pages to space admins.

![image](https://i.imgur.com/hfogx54.png)
![image](https://i.imgur.com/jvXMyRP.png)

Also I've found that the CKEditor has his own content filtering [feature](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_acf.html) ready to be configured, it does certainly support removing unwanted tags, so we'll be using that.

**Comment by bumi** [comment]
whoot nice! I'd actually say we should already deploy this and publish the landing page Karim has written. 
can you make a PR?

re CKEditor: so CKEditor is doing that filtering on the server?

**Comment by craxrev** [comment]
but wait, no sensitization is performed when submitting the HTML, we shouldn't publish it until we do so.
concerning the CKEditor as mentioned in the link in the last comment :

> **Provide a real WYSIWYG editor**:
ACF should not be used as a replacement to server-side security filtering that sanitizes entered data. If, however, a server-side filter exists, ACF will be its perfect companion that ensures the users will see exactly the same content in the editor as after saving it.
Suppose that server-side filter does not allow the <iframe> tag. If users would be able to paste it into CKEditor and see the iframe inside the WYSIWYG area, would that not be confusing?

so the editor is doing its filtering on the client side, meaning when choosing in the editor to add html manually (source btn), when returning to the view, filtered-out tags will get automatically removed.

**Comment by craxrev** [comment]
We could publish it on the testing server as it is right now, and let @KarimChabrak do his magic in HTML, meanwhile I'll be working on the server-side sanitization.

**Comment by bumi** [comment]
so if it is doing on the client it is not enough - we can not rely on any user input. 

but yeah, let's push it online on the testing server and add the yii built in sanitizing.
