### ISSUE TITLE
Menatabadol cant make transfer

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#200]
When trying to make a transfer from this account, i get error message below
https://menatabadol.org/space/marketplaces/xcoin/account?id=6

{
    "url": "/space/marketplaces/xcoin/transaction/transfer?accountId=6",
    "status": 500,
    "response": "<pre>PHP Recoverable Error &#039;yii\\base\\ErrorException&#039; with message &#039;Object of class humhub\\modules\\space\\models\\Space could not be converted to string&#039; \n\nin /home/menayefo/public_html/protected/modules/xcoin-i4c/views/transaction/transfer.php:22\n\nStack trace:\n#0 /home/menayefo/public_html/protected/modules/xcoin-i4c/views/transaction/transfer.php(22): yii\\base\\ErrorHandler-&gt;handleError(4096, &#039;Object of class...&#039;, &#039;/home/menayefo/...&#039;, 22, Array)\n#1 /home...",
    "textStatus": "error",
    "xhr": {
        "readyState": 4,
        "responseText": "<pre>PHP Recoverable Error &#039;yii\\base\\ErrorException&#039; with message &#039;Object of class humhub\\modules\\space\\models\\Space could not be converted to string&#039; \n\nin /home/menayefo/public_html/protected/modules/xcoin-i4c/views/transaction/transfer.php:22\n\nStack trace:\n#0 /home/menayefo/public_html/protected/modules/xcoin-i4c/views/transaction/transfer.php(22): yii\\base\\ErrorHandler-&gt;handleError(4096, &#039;Object of class...&#039;, &#039;/home/menayefo/...&#039;, 22, Array)\n#1 /home/menayefo/public_html/protected/vendor/yiisoft/yii2/base/View.php(336): require(&#039;/home/menayefo/...&#039;)\n#2 /home/menayefo/public_html/protected/vendor/yiisoft/yii2/base/View.php(254): yii\\base\\View-&gt;renderPhpFile(&#039;/home/menayefo/...&#039;, Array)\n#3 /home/menayefo/public_html/protected/humhub/modules/ui/view/components/View.php(111): yii\\base\\View-&gt;renderFile(&#039;/home/menayefo/...&#039;, Array, Object(humhub\\modules\\xcoin\\controllers\\TransactionController))\n#4 /home/menayefo/public_html/protected/vendor/yiisoft/yii2/web/Controller.php(49): humhub\\modules\\ui\\view\\components\\View-&gt;renderAjax(&#039;transfer&#039;, Array, Object(humhub\\modules\\xcoin\\controllers\\TransactionController))\n#5 /home/menayefo/public_html/protected/modules/xcoin-i4c/controllers/TransactionController.php(92): yii\\web\\Controller-&gt;renderAjax(&#039;transfer&#039;, Array)\n#6 [internal function]: humhub\\modules\\xcoin\\controllers\\TransactionController-&gt;actionTransfer(&#039;6&#039;)\n#7 /home/menayefo/public_html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)\n#8 /home/menayefo/public_html/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\\base\\InlineAction-&gt;runWithParams(Array)\n#9 /home/menayefo/public_html/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\\base\\Controller-&gt;runAction(&#039;transfer&#039;, Array)\n#10 /home/menayefo/public_html/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\\base\\Module-&gt;runAction(&#039;xcoin/transacti...&#039;, Array)\n#11 /home/menayefo/public_html/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\\web\\Application-&gt;handleRequest(Object(humhub\\components\\Request))\n#12 /home/menayefo/public_html/index.php(27): yii\\base\\Application-&gt;run()\n#13 {main}</pre>",
        "status": 500,
        "statusText": "error"
    },
    "dataType": "html",
    "html": "<pre>PHP Recoverable Error &#039;yii\\base\\ErrorException&#039; with message &#039;Object of class humhub\\modules\\space\\models\\Space could not be converted to string&#039; \n\nin /home/menayefo/public_html/protected/modules/xcoin-i4c/views/transaction/transfer.php:22\n\nStack trace:\n#0 /home/menayefo/public_html/protected/modules/xcoin-i4c/views/transaction/transfer.php(22): yii\\base\\ErrorHandler-&gt;handleError(4096, &#039;Object of class...&#039;, &#039;/home/menayefo/...&#039;, 22, Array)\n#1 /home...",
    "error": {},
    "errorThrown": "",
    "validationError": false
}

**Comment by gdalyy** [comment]
@ZouaouiK please fix this as discussed on slack
