### ISSUE TITLE
Error message when accepting space membership requests

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#206]
I get this screeen when I accept membership request in the space. THE USER AFTER ACCEPTING BECAME A MEMBER AS IT SHOULD BE.

![grafik](https://user-images.githubusercontent.com/41925899/102796862-28eeab80-43af-11eb-8b1b-3cb7fc1ba796.png)

**Comment by gdalyy** [comment]
I think this is related to ether gas fees, it works normal when ethereum is disabled , @haythem96
