### ISSUE TITLE
Alternative Crowd Funding options

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#215]
Currently, there is only the option to start crowd funding campaigns in exchange of space issued token at user set rate.

As challenge initiator, I would like to have also following options besides of the current option (alternative 1):
-Alternative 2- Initiate a funding challenge whithout receiving coins.
-Alternative 3- Initiate a funding campaign, select a specific coin that projects can offer and set a fixed exchange rate.

**CHALLENGE CREATION**
In the creation process of challenges, the selection of options and inpout is set. 
![grafik](https://user-images.githubusercontent.com/41925899/110252141-40880a00-7f84-11eb-8bf1-2fb354357808.png)

**PROJECT SUBMISSION**
In alternative 1, project sumbission is like before

In alternative 2 and 3, projects will not need see this when adding a project:

![grafik](https://user-images.githubusercontent.com/41925899/110251515-154feb80-7f81-11eb-9826-480836662ef0.png)

In alternative 3, projects will be asked to select the account from where they can send the requested Coins to the crowdfunding account. **Investors can invest as long there are coins in the crowdfunding account.**

![grafik](https://user-images.githubusercontent.com/41925899/110251559-5d6f0e00-7f81-11eb-95dc-a09ef014860a.png)

**Comment by KarimChabrak** [comment]
@rafinala as discussed, In alternative 2 and 3, you do not issue coins when a project makes a submission.

In alternative 3, Project submitter will have in the final submission step a window to either select an account where (Offered) coins are available or can click on a button "I will send rewarding COINs later to activate my campaign".

**Comment by KarimChabrak** [comment]
Issue 1: 
Using alternative 3, It creates 2 campaigns
https://dev.coinsence.org/space/meet-africa/xcoin/funding

**Comment by KarimChabrak** [comment]
Issue 2: 
Using alternative 1, user does not receive space coin when investing coins.
https://dev.coinsence.org/space/investment-coin/xcoin/account?id=598

**Comment by KarimChabrak** [comment]
Issue 3: 
Using alternative 2 (no rewarding). I can not invest in project 
https://dev.coinsence.org/space/test12345678/xcoin/funding/overview?fundingId=82
![grafik](https://user-images.githubusercontent.com/41925899/116820531-fb441b00-ab75-11eb-9e92-f55e2fcf658a.png)

**Comment by KarimChabrak** [comment]
Issue 4:
In alternative 3,  the last step when adding a project should be like this.
PROJECT OWNER CAN SEND "REWARDING COINS" TO CROWFFUNDING ACCOUNT

![grafik](https://user-images.githubusercontent.com/41925899/116821642-f897f480-ab7a-11eb-8c1d-1b68cdeecd8b.png)

LATER, INVESTOR INVEST "REQUESTED COINS" AND RECEIVE "REWARDING COINS"
Here, we should not counting rewarding coins in the progress of the campaign. It should be the requested coins that is counted.

![grafik](https://user-images.githubusercontent.com/41925899/116821735-59bfc800-ab7b-11eb-8244-f20a2d1e2e88.png)

**Comment by KarimChabrak** [comment]
**Alternative 3 creates following error when adding a project. The project is then added, but project owner is not asked to send rewarding coins to project.**


An unexpected server error occurred. If this keeps happening, please contact a site administrator.

{
    "url": "/space/testchallenges/xcoin/funding/new?challengeId=21",
    "status": 500,
    "response": "<pre>Exception (Unknown Property) &#039;yii\\base\\UnknownPropertyException&#039; with message &#039;Getting unknown property: humhub\\modules\\xcoin\\models\\Funding::specific_sender_account_id&#039; \n\nin /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/base/Component.php:154\n\nStack trace:\n#0 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(296): yii\\base\\Component-&gt;__get(&#039;specific_sender...&#039;)\n#1 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/helpers...",
    "textStatus": "error",
    "xhr": {
        "readyState": 4,
        "responseText": "<pre>Exception (Unknown Property) &#039;yii\\base\\UnknownPropertyException&#039; with message &#039;Getting unknown property: humhub\\modules\\xcoin\\models\\Funding::specific_sender_account_id&#039; \n\nin /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/base/Component.php:154\n\nStack trace:\n#0 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(296): yii\\base\\Component-&gt;__get(&#039;specific_sender...&#039;)\n#1 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/helpers/BaseHtml.php(2193): yii\\db\\BaseActiveRecord-&gt;__get(&#039;specific_sender...&#039;)\n#2 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/helpers/BaseHtml.php(1323): yii\\helpers\\BaseHtml::getAttributeValue(Object(humhub\\modules\\xcoin\\models\\Funding), &#039;specific_sender...&#039;)\n#3 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/helpers/BaseHtml.php(1412): yii\\helpers\\BaseHtml::activeInput(&#039;hidden&#039;, Object(humhub\\modules\\xcoin\\models\\Funding), &#039;specific_sender...&#039;, Array)\n#4 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/widgets/ActiveField.php(429): yii\\helpers\\BaseHtml::activeHiddenInput(Object(humhub\\modules\\xcoin\\models\\Funding), &#039;specific_sender...&#039;, Array)\n#5 /var/www/coinsence_dev/protected/modules/xcoin/views/funding/add-specific-account.php(37): yii\\widgets\\ActiveField-&gt;hiddenInput()\n#6 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/base/View.php(336): require(&#039;/var/www/coinse...&#039;)\n#7 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/base/View.php(254): yii\\base\\View-&gt;renderPhpFile(&#039;/var/www/coinse...&#039;, Array)\n#8 /var/www/coinsence_dev/protected/humhub/modules/ui/view/components/View.php(111): yii\\base\\View-&gt;renderFile(&#039;/var/www/coinse...&#039;, Array, Object(humhub\\modules\\xcoin\\controllers\\FundingController))\n#9 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/web/Controller.php(49): humhub\\modules\\ui\\view\\components\\View-&gt;renderAjax(&#039;add-specific-ac...&#039;, Array, Object(humhub\\modules\\xcoin\\controllers\\FundingController))\n#10 /var/www/coinsence_dev/protected/modules/xcoin/controllers/FundingController.php(171): yii\\web\\Controller-&gt;renderAjax(&#039;add-specific-ac...&#039;, Array)\n#11 [internal function]: humhub\\modules\\xcoin\\controllers\\FundingController-&gt;actionNew(&#039;21&#039;)\n#12 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)\n#13 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\\base\\InlineAction-&gt;runWithParams(Array)\n#14 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\\base\\Controller-&gt;runAction(&#039;new&#039;, Array)\n#15 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\\base\\Module-&gt;runAction(&#039;xcoin/funding/n...&#039;, Array)\n#16 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\\web\\Application-&gt;handleRequest(Object(humhub\\components\\Request))\n#17 /var/www/coinsence_dev/index.php(27): yii\\base\\Application-&gt;run()\n#18 {main}</pre>",
        "status": 500,
        "statusText": "Internal Server Error"
    },
    "dataType": "html",
    "html": "<pre>Exception (Unknown Property) &#039;yii\\base\\UnknownPropertyException&#039; with message &#039;Getting unknown property: humhub\\modules\\xcoin\\models\\Funding::specific_sender_account_id&#039; \n\nin /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/base/Component.php:154\n\nStack trace:\n#0 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(296): yii\\base\\Component-&gt;__get(&#039;specific_sender...&#039;)\n#1 /var/www/coinsence_dev/protected/vendor/yiisoft/yii2/helpers...",
    "error": {},
    "errorThrown": "Internal Server Error",
    "validationError": false
}

**Comment by KarimChabrak** [comment]
Alternative 3 is still forcing integer exchange rate when creating challenge

**Comment by KarimChabrak** [comment]
Alternative 2 give this when adding a project

![grafik](https://user-images.githubusercontent.com/41925899/117181875-f7aecf00-add5-11eb-8b3b-4d4fda27fb9a.png)

**Comment by KarimChabrak** [comment]
Alternative 3. I am still not able to invest in project in Alternative 3, even though i have allocated rewarding coins.

https://dev.coinsence.org/space/sscs/xcoin/funding/overview?fundingId=86

**Comment by KarimChabrak** [comment]
@rafinala 

**on Dev**, your changes are not anymore there when creating a challenge.


**On dev and on prod**, When addin a project, it shows the wrong icon in "provided coins". 
It shows the icon on the space where challenge has been created:
Ib option 1, we need to show
- the icon on the space selected by project owner or show no icon if project owner did not create yet a space.



![grafik](https://user-images.githubusercontent.com/41925899/118287725-0717d180-b4d4-11eb-94ef-754c1fbfad85.png)

**Comment by rafinala** [comment]
hello @KarimChabrak  i havent touched anything related to alternative 1 , but i'll check it

**Comment by rafinala** [comment]
hello @KarimChabrak ok i will check them

**Comment by KarimChabrak** [comment]
Dear @rafinala This is a strange issue.

This project was created with the corresponding funding account
https://community.coinsence.org/space/business-game/xcoin/funding/overview?fundingId=277
https://community.coinsence.org/space/business-game/xcoin/account?id=11301

But when user has invested, the COINs have been sent to this account
https://community.coinsence.org/space/jci-coin/xcoin/account?id=11276

VERY STRANGE. PLEASE CHECK
