### ISSUE TITLE
Filtering proposed sender accounts based on requested asset

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#22]
As crowd investor, I would like to see when selecting sender account only my managed accounts which have a p ositive balance of the requested asset, to save time.

![image](https://user-images.githubusercontent.com/41925899/50848936-ed9b7380-1375-11e9-9e2b-c310c62b105f.png)

**Comment by KarimChabrak** [comment]
@gdalyy  
Please check if you could add this soon to avoid user confusion when user for not have requested coins.     
When investing, show only the accounts which include a positive amount of the requested asset. In case user does not have requested asset, show the message "sorry, you have no accounts which includes the coins requested here"

**Comment by bumi** [comment]
no, we never can add anything soon. please, let's go though some prioritization process and stick to what we planned there.
