### ISSUE TITLE
Investigate DAOstack

### ISSUE THREAD

**Issue by bumi** [Coinsence/meta#23]
DAOstack has a few tools published: https://github.com/daostack
we should investigate if those are helpful for us and if we can use their tools for our setup.

**Comment by haythem96** [comment]
what should we do for this XD @bumi ... we may leave it open in th progress for a while...

**Comment by bumi** [comment]
I think from what we have seen and talked about we decided aragonOS is a good choice. 
so even though we did not write a nice pro and contra decision list I'd say we can close this for now?

**Comment by haythem96** [comment]
I agree...
