### ISSUE TITLE
Hide space menu items when there is no relevant content

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#231]
I propose to hide following menu items when there is no content. These items shall stay visible for space admins.
-Hide Challnge when space did not create challenges.
- Hide proposal, when space did not send any proposal.
- Hide Marketplaces, when space did not create any marketplace
- Hide products, when space did to create any product yet.

![grafik](https://user-images.githubusercontent.com/41925899/112031234-63491f80-8b3b-11eb-95b5-f8bc141629c5.png)

**Comment by gdalyy** [comment]
I dont agree on above changes,  from a UX perspective menus should not change depending on users (with same role) profiles.

**Comment by KarimChabrak** [comment]
In most of the spaces, user will click on them and will not find anything. 

Based on current exchange with many potential group which hopefully will use our platform, they want to be able to customize the space menu.

**Comment by KarimChabrak** [comment]
@gdalyy as each space shall be responsible how to deal with his space members, we could maybe add the option to space admins to hide manually selected space menu buttons.

**Comment by gdalyy** [comment]
Still don't agree because as I said we should not have different menus for same UI and for same user role but as you wish.

PS: menus may change depending on user role for example admin can see different menus than normal user, but all normal users should see same menus on every space, otherwise they will get confused.

**Comment by KarimChabrak** [comment]
@gdalyy i can understand you position, if we would have mostly Coinsence users which will join the platform and join some spaces. But the typical user is a member of association/community/project who will join and will be mostly only be interacting within his target space.  

These are the arguments why:
- A typical user will be active in a single space when they join the platform. They might join after some month an other community or create their own project space.
- Each space might be difffrent and space owner would need to improve the experience of their members. These space will be mostly the first landing space when their members register. These members will be confused if there are menus who do not lead to any content. So, we can not enfore our menu structure on all space. 
- Some space will not need any of marketplace, corwdfunding, etc... but just accounts. Having all these on the menu will increase complexity and degrade user experience.

We got often the feedback of potential space creators, "i dont need this button or this button in the menu. I must always explain my members this button and tell them that it is not relevant...."

**Comment by gdalyy** [comment]
Lgtm 👍

**Comment by KarimChabrak** [comment]
Literally Garbage To Me   or does LGTM mean something else ;-)

**Comment by gdalyy** [comment]
Looks good to me 😅🙄
