### ISSUE TITLE
Setup UNICEF integration

### ISSUE THREAD

**Issue by bumi** [Coinsence/meta#25]
One of the requirements of UNICEF was to push realtime data to their dashboard. 
We need to setup this integration.

**Comment by bumi** [comment]
here is the unicef document:
https://docs.google.com/document/d/1E-PkJgOxfZ48_CWzYhSWdXAaXV8_dovYJqmIExcCrL0/edit

**Comment by craxrev** [comment]
Any updates on this issue @bumi @KarimChabrak ? If there's any new information, please write it down here. I should start working on this asap.
