### ISSUE TITLE
Enable creation of accounts for tasks

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#26]
As task manager, I would like to allocate a certain amount of coins to a task. 
From the single task, i would like to create an account within the space. 

- The account name shall be linked to the task id. 
- The manager of this account shall be the task responsible.

**Comment by gdalyy** [comment]
@KarimChabrak, i've managed until now to automatically create and account when a task is created but there is some issues : 
- How should i name the new Account ? (see picture below)
  - Task#{taskID}
  - Task Account : {taskName}
  - Task Account ({taskName}) 

![fireshot capture 144 - test space - coinsence_ - http___coinsence_index php](https://user-images.githubusercontent.com/13172404/52541877-40fc4980-2d9a-11e9-8497-0bf23a87b40e.png)

- When creating a task, many responsibles are possible  in the task form so which one should i make  the account responsible ? or sould we make one possible responsible for a task ?

**Comment by KarimChabrak** [comment]
@gdalyy 
I would name the account as 
- Task#{taskID}

I will open an other issue where i will propose the intruduce account categories.  In our case here, the account categogie will be later "tasks". 

I will then add an other issue where the link to the task shall be shown in the account list.

Preferably, the account responsible shall be the task responsible. 
- If any task responsible can approve the task, then any task responsible can initiate the  transaction from the task account.
- If all the task responsibles have to approve the task,  then transaction from the task account can be only initated when all approve.
Check please how the current approval process in the task is, and then let's check how to adapt this to the account.

**Comment by gdalyy** [comment]
@KarimChabrak, 

- I'am okay with your first answer.
- But for the second one, i'm not talking about transaction initiation, i'm talking about in case we have many responsibles which one should i make the account manager ? because every account within a space has one an only one manager.

**Comment by gdalyy** [comment]
So as discussed, 

A task could have only one responsible who will be also the account manager and may have many workers (users).

**Comment by gdalyy** [comment]
For the moment we will stick with :

- One responsible for a task 
- One worker for a task

**Comment by KarimChabrak** [comment]
Good job 

see the following issues
https://github.com/Coinsence/meta/issues/32
https://github.com/Coinsence/meta/issues/33
