### ISSUE TITLE
Set as "assigned user" for task my payment account

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#27]
As "assigned user" for a task, I would like when I get a task assigned to me to set the payment account. 
I can select any account i want. When task is accompliched by me and accepted by the responsible user, the coins shall be then transferred to this account

**Comment by KarimChabrak** [comment]
Currently, the button appears, but does not work.

![image](https://user-images.githubusercontent.com/41925899/54091102-4c806780-437c-11e9-8521-838d2dabe9ee.png)

**Comment by gdalyy** [comment]
The button works , but you don't have accounts that's why the list is empty.
This is what happens when i work without prior mockups. 
Any way it's not a bug but why should have a notice to tell the user that he should create an account so that he can choose it as target account and then start the task

**Comment by craxrev** [comment]
@gdalyy, you can make it disabled and if hovered, there'll be a small tooltip that tells him that there's no accounts? what do you think?

**Comment by KarimChabrak** [comment]
my thinking was that user can select any account. The reason is that maybe your boss or your company shall get the money.
like when making transactions, user first selects account owner then selects account name+manager

**Comment by KarimChabrak** [comment]
maybe we should also open a new issue where we should automatically
- enable the  accounting module for each user 
- make for each user a default personal account

and we remove the button for the moment where user can create an additional personal account.

This  makes life easier for the user.

**Comment by gdalyy** [comment]
Re : 
> enable the accounting module for each user & make for each user a default personal account 

Soundsgood to me.

For the shown accounts : What type of account should i display ? all type of accounts ? personal accounts only ? other spaces account managed by the user ? ...

**Comment by gdalyy** [comment]
@craxrev your idea is good but by enabling accounting module for each user and making for each user a default personal account i think there is no need to disable the button and to add a tooltip.

**Comment by craxrev** [comment]
I agree 👍

**Comment by KarimChabrak** [comment]
> @craxrev your idea is good but by enabling accounting module for each user and making for each user a default personal account i think there is no need to disable the button and to add a tooltip.

Check this. https://github.com/Coinsence/meta/issues/27#issuecomment-471367632

**Comment by KarimChabrak** [comment]
> ll type of accounts ? personal accounts only ? other spaces account managed by the user ? ...

As it is done for transactions. Any account can be selected, not only those related to the user. Check the process how a TARGET account is selected when someone makes a transaction.
