### ISSUE TITLE
Funding account after campaign cancellation

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#275]
Currently, when campaign is cancelled, we are sending back transactions related to investment. 

**But we are hiding funding account, which still have coins.** 

I propose following:

- Not hide funding account after cancellation.
- User can disable funding account manually by showing him the button which is already implemented.

Valid allways when disabling an account, following text should be also added to the popup that appears in small ("When disabling account, all COINs will be transferred to space default account.")

![grafik](https://user-images.githubusercontent.com/41925899/120238620-d28a7080-c25c-11eb-877d-17115d0880d7.png)

**Comment by KarimChabrak** [comment]
@rafinala 

Disabling account should be only shown after campaign cancellation.
Please add this text to popup when disabling account. ("When disabling account, all COINs will be transferred to space default account.")

**Comment by KarimChabrak** [comment]
CAncelling following campaign on prod seems not be able to sens back invested coins. 

https://community.coinsence.org/space/test23jul2021/xcoin/funding/overview?fundingId=330

![grafik](https://user-images.githubusercontent.com/41925899/127559455-8ad4d907-7b6e-4301-adc5-74cf40483a84.png)

**Comment by rafinala** [comment]
i will check it asap
