### ISSUE TITLE
Setup a blog

### ISSUE THREAD

**Issue by bumi** [Coinsence/meta#29]
To easily share blog posts and photos we need to setup a blog.
maybe we can start with medium but use our own domain? blog.coinsence.org - is that possible? 

Alternatively we can use a static site generator like https://gohugo.io/ which would be my preference. - They have also a huge list of themes: https://themes.gohugo.io/ e.g. this could be enough: https://themes.gohugo.io/hugo-dgraph-theme/

- [ ] enable sub domain
- [x] cleanup repo from demo content
- [x] add author configs
- [ ] publish first content
- [ ] ~~configure google_analytics~~
- [ ] ~~configure disqus~~
- [ ] ~~setup mailchimp-list subscription~~
- [x] add a readme describing how to run it locally, how to deploy, how to write a post
- [x] navigation to link back to the main coinsence page and other pages (like login on community.coinsence.org)
- [x] remove the "featured" articles block
- [x] remove the newsletter for now
- [x] remove the the explore block

**Comment by SeifBa** [comment]
You can put a link for a medium blog with a cover photo and description of coinsence. but the url will be like that : https://medium.com/coinsence
or we can use steemit !

**Comment by bumi** [comment]
nah, we must own and be in control of the content/domain - so this is imo not an option. 
so I'd suggest we setup a blog using a static page generator as described above.

**Comment by MalekTN** [comment]
Hi guys, sorry for catching up late, @bumi the link for the theme you suggested is broken, can you attach it again please? i wanna take a look at it

**Comment by bumi** [comment]
this one: https://themes.gohugo.io/hugo-dgraph-theme/ - just a pretty plain simple one?

**Comment by MalekTN** [comment]
yeah i agree, its simple and easy to use. just what we need!
so should i add the sections that saif proposed in the trello card?

**Comment by lemsadelavega** [comment]
Heeeeey ! I am finally there ! Well i don't agree really for using the static generator, using medium will be better for our exposure, SEO, etc... moreover the crypto, crowdfunding, design etc are subjects and topics that people look for a lot on Medium

So the best thing would be to host it on medium and Malek and I, will work on the UI of the page to get something very similar to this : https://uxdesign.cc/ who is one of the most read blog about UXdesign

What do you think guys ?

**Comment by lemsadelavega** [comment]
As you can see AJ&Smart which is one of the most famous design agency use medium for their blog and its rocking a lot https://blog.ajsmart.com/ so we def should consider this option, simple and efficient !

**Comment by MalekTN** [comment]
fine by me 👍 
great idea!

**Comment by bumi** [comment]
The reason why I dislike tools like medium is, that we try to build decentralized solutions but hand over all our content and users to one single company.  - so that is more ideological. 
medium is tracking users, collecting user data and we are supporting that, by hosting our content there. 

That being said, I am OK with using medium IF it is running on our own domain and we have the chance to move somewhere else in the future. 
- the examples suggest that we can use our own domain?

**Comment by bumi** [comment]
interesting content on [blog.ajsmart.com/](https://blog.ajsmart.com/)

**Comment by craxrev** [comment]
I think it's feasible, but it is not a straightforward process, needs some tinkering but was reading about it not so long ago in [this](https://medium.com/@Rogier.Slag/setting-up-a-free-custom-domain-for-your-medium-account-336c21229254) blog post, but I dont know if it is outdated or not, though medium was offering custom domain, but it is already deprecated!

**Comment by lemsadelavega** [comment]
Yes I understand what you mean Michael, but actually we are currently newcomers, no one really know who we are, so we should use some leverage to put Coinsence forward by going where our potential users could be :) and indeed after we could move to our self host blog.

**Comment by bumi** [comment]
seem they don't offer custom domains anymore? https://help.medium.com/hc/en-us/articles/115003053487-Custom-Domains-service-deprecation ?

**Comment by lemsadelavega** [comment]
that really sucks indeed its no longer available, i propose then https://ghost.org/features/  what do you think ?

**Comment by lemsadelavega** [comment]
![image](https://user-images.githubusercontent.com/25116389/53427099-94040c80-39e8-11e9-892f-22e169bc7175.png)

As you can see it's pretty much looking to medium design guidelines and used by the most commun startup and company

**Comment by bumi** [comment]
that means you care about the design? that should be similar to the one in the screenshot? 
the nice thing about static pages is that maintenance is minimal and we don't have to care about that. 
hosted ghost costs 29USD/months?

**Comment by lemsadelavega** [comment]
Definitely I care about it ! But yea i thought there was a kind of free plan but there isn't... well so we use hugo ? but we will have to work on the design and not just using some template or at least find the right template

**Comment by bumi** [comment]
:+1: ok, do you see a theme we can base on? https://themes.gohugo.io/

**Comment by lemsadelavega** [comment]
Well actually I didn't find something outstanding or that is close to Medium or ghost design, maybe we should selected the closest one to them and the devs make some changes on it, would it be possible ?

**Comment by bumi** [comment]
yep, that's what I mean. chose a base theme and then adjust the design for our needs. 

but also keep in mind that currently we do not have any posts, and we are probably slow in writing new ones currently. 
it will also be possible to update the theme later according to the amount of posts.

**Comment by lemsadelavega** [comment]
ok great then, I am actually talking with Malek about our design needs for the blog so he will prepare some mockups and we will choose a template

**Comment by bumi** [comment]
:+1:

**Comment by MalekTN** [comment]
Hi guys, so i'm going to start customising the theme https://spreadprivacy.com/ 

so i want to know if there's functionnalities that you propose we add to it (search, login&signup, etc...)

**Comment by bumi** [comment]
I'd say no login, search, etc. - there is no functionality that we need login for, is there? 
and we don't have much content, so also no search should be needed. 

also keep in mind, that we will have hardly any content in the next weeks - spreadprivacy.com seems to look good with quite some posts.

And if we use https://gohugo.io/ - we need to respect the template syntax and structure of the tool.

**Comment by bumi** [comment]
I'd say no login, search, etc. - there is no functionality that we need login for, is there? 
and we don't have much content, so also no search should be needed. 

also keep in mind, that we will have hardly any content in the next weeks - spreadprivacy.com seems to look good with quite some posts.

And if we use https://gohugo.io/ - we need to respect the template syntax and structure of the tool.

**Comment by lemsadelavega** [comment]
Agree with @bumi but don't find something close to what we want, isn't there another CMS we can look for ?

**Comment by bumi** [comment]
how would another CMS solve the problem? - isn't it more a problem of the design of the suggested page?

**Comment by lemsadelavega** [comment]
coz we didn't find the design wanted and don't if the guys are ok with working on a hugo template to make it as we want ?

**Comment by craxrev** [comment]
found a medium like template https://wowthemesnet.github.io/mediumish-theme-jekyll/, it's based on **jekyll** but we can migrate it to **hugo**, what do you think guys? could we use it as a base template?

**Comment by MalekTN** [comment]
I like it!

**Comment by bumi** [comment]
:+1: (can also use jekyll if we want)

**Comment by craxrev** [comment]
Alright coowl, I'll deploy it later on the dev server and see if it does need any changes from the design team

**Comment by bumi** [comment]
I'd suggest we simply host it on github (using github pages) or netlify. no need to configure anything on our servers.

**Comment by craxrev** [comment]
oh that's better, we'll do 👍

**Comment by MalekTN** [comment]
allright then, see if there is any changes that suits our needs and let me know!

**Comment by lemsadelavega** [comment]
daaaamn well done @craxrev how you manage to find it haha ! 
Definitely in, for this one

**Comment by craxrev** [comment]
Hihihii, just the old way: google :sweat_smile: 
btw, I'm installing it r n on github, having some "hosting" issues but will be online in a few minutes.. hopefully!

**Comment by bumi** [comment]
let me know if you need help. I'm hosting my website also on github.

**Comment by craxrev** [comment]
Actually, I'm working on integration the template with the github pages, there's something about adding remote_theme: username/repo to the _config.yml, but not sure yet, so yeah.. I need guidance here :sweat_smile:

**Comment by craxrev** [comment]
oh, I've created a new repo named [coinsence.github.io](https://github.com/Coinsence/coinsence.github.io), not sure if yoou've seen it

**Comment by craxrev** [comment]
I'm following this [article](https://help.github.com/en/articles/using-jekyll-as-a-static-site-generator-with-github-pages) from github

**Comment by bumi** [comment]
I'd follow this: https://wowthemesnet.github.io/mediumish-theme-jekyll/about#usingmediumish

so you actually should adjust the _config.yml

and the tutorial maybe: https://jekyllrb.com/docs/step-by-step/01-setup/

do you have it running locally?

**Comment by craxrev** [comment]
yes, actually I've just finished configuring it on live

**Comment by craxrev** [comment]
The website is [live](https://coinsence.github.io/index.html) now, we can begin changing and adding content, @MalekTN and @lemsadelavega you can start interacting and see if there's any improvment that can be made.

**Comment by MalekTN** [comment]
allright great!

**Comment by bumi** [comment]
@craxrev what happened to the blog?

**Comment by craxrev** [comment]
I've disabled the blog github pages because no content is published yet but you can get it back by renaming the blog repo

**Comment by craxrev** [comment]
But still need to discuss wether we use a fork or a cloned version of the templates

**Comment by bumi** [comment]
fork or clone is pretty much the same. 

let's add todos to this issue of what you think is missing.

**Comment by bumi** [comment]
what is the status here? I'd like to net spend too much time on the whole blog setup :)  and rather optimize it step by step also when we have more posts.

**Comment by craxrev** [comment]
I'm cleaning up the blog from demo content and testing locally changes and also waiting for design team to give me new assets (images, fonts, wordings)

**Comment by craxrev** [comment]
For reference, https://github.com/Coinsence/meta/blob/master/docs/blogging.md is where you can find the blog documentation, if there's any thing that it is not clear, please inform us to better enhance it.
