### ISSUE TITLE
Make task account balance visible in the task module

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#33]
The balance on task accounts shall be visible for each task in the task list.

**Comment by bumi** [comment]
this should be displayed next to the numer of comments? 

which icon do we use? do we have a coin icon?

**Comment by gdalyy** [comment]
@KarimChabrak , i working on this issue right now and i'm wondering where to display the balance like @bumi said ?
And also can task account have multiple assets so multiple balances or it supports only space asset ?

**Comment by bumi** [comment]
re multiple balances: I think we should discuss that in a broader product round? 
because I think it gets complicated there? (thus I'd say we should only have one - the space's currency)

**Comment by KarimChabrak** [comment]
@gdalyy 
I would enable only one type of assets per task account. But this should not be forced to be the space currency.

I would display the balance next to the number of comments.

**Comment by KarimChabrak** [comment]
> which icon do we use? do we have a coin icon?
currently we use space profile picture as icon to the space generated coin. I have added the issue #36  to introduce dedicated coin icons.

**Comment by gdalyy** [comment]
@KarimChabrak 

> I would enable only one type of assets per task account.

Where this should be done? in the task creation form or after creating the task, go to accounts list, edit the account and choose the asset ?

**Comment by bumi** [comment]
I think this is a good example where we have to talk product.... 
making the coin configurable per tasks adds quite some complexity for the user and the product - at least from a development perspective this has to be somehow managed. 
similarly #36 - means we have to develop the whole management of those files and people have to understand how to create such images and icons. 

do we need this? does this add real value to our product that is worth the complexity?

**Comment by bumi** [comment]
also we should consider if this is really needed in a first release of the account->task feature.

**Comment by KarimChabrak** [comment]
@gdalyy    
I think also that creating rules for account, e.g. only accepting a single asset type is a bit too komplex for the moment. We should not spend time on this.

What is the most easy way at the moment?

I would say, the easiest ways would be to simply add a symbol on the task list which is linking to the task account overview.

**Comment by gdalyy** [comment]
Done

**Comment by gdalyy** [comment]
Should i deploy this on the dev platform ? if so i need to undo #34 (already deployed), because as discussed it may have ulterior impact or should i keep both of them !

**Comment by KarimChabrak** [comment]
@gdalyy 
Why is this related to #34 ?

**Comment by KarimChabrak** [comment]
To my understanding, 
When i create or edit a task, I select if i want to create an account for the task. If I create an account, the link to the task account becomes visible on the task list.

**Comment by gdalyy** [comment]
Because those two features : 

- Optional account creation
- Account visible on task list

are on different branches. And now on the dev platform we are on the branch associated to `tup#34` so you can test the feature, if we will keep those two features i'll merge code into one branch, if not we will have only approved feature available on dev platform. I hope i've explained well

**Comment by gdalyy** [comment]
@KarimChabrak , i'm only asking if we will stay with the tup#34 because as you see @bumi is not 100% for adding this for now, if not i need to discard changes made on its branch

**Comment by KarimChabrak** [comment]
I am not clear why tup#34 should not been added.

**Comment by bumi** [comment]
@KarimChabrak did you reed my comments: https://github.com/Coinsence/humhub-modules-tasks/pull/2#pullrequestreview-204906607

**Comment by gdalyy** [comment]
I'm not saying that we should not add it, i'm just asking, i already resolved this issue and sure i don't want to drop it hhh. 

Once we all approve to keep this feature i'll make a PR. What do you think @bumi & @KarimChabrak ?

**Comment by bumi** [comment]
let's discuss about if accounts should be optional in the PR or the related issue. 
this one is about making the account balance visible.
