### ISSUE TITLE
Task account creation shall be optional

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#34]
When I create a task, I do not want to be forced to create an account. This shold be optional

**Comment by bumi** [comment]
why? do we reeally need this exception right now?

**Comment by KarimChabrak** [comment]
> why? do we reeally need this exception right now?

If we leave this as it is now, every task will create an account. In most of the cases an account is not needed.

**Comment by bumi** [comment]
if in **most cases** an account is not needed, why do we develop this feature in the first place?

again a topic where we need to talk product: we can not just throw features on it.

**Comment by KarimChabrak** [comment]
@bumi 

Spaces which distibutes coins need a way for
- To show for what tasks coins have been distributed.
- Achieve a clear agreement between task responsible and task worker
- Allocated coins to task to show potential worker the offered compansation for tasks.
- Enable co-funding and prioritization of tasks. 

But I fully agree that we need to better better joined way to prioritize issues here.

**Comment by bumi** [comment]
these are reasons why it needs to be optional? then I don't understand the answers.

**Comment by KarimChabrak** [comment]
@bumi 
You asked why we develop this feature in first place. The reasons above a why we need accounts for tasks and not why this shall be optional

**Comment by bumi** [comment]
yep, but I do not understand the answers. - imo they are not related to the question why we need to have accounts optional.

and my question about why we developed the feature in the first place relates to your comment, that in "**most of the cases** an account is not needed". 

we have to work on our USPs and the best tool for "most of the cases" -> a topic for defining the product. and we need to also get Salem on board here. 

you've recently posted this image: https://coinsence.slack.com/archives/CG1KBVC7R/p1550509103004800 - but we still behave in the opposite way and add more options :)
