### ISSUE TITLE
Create project Coinsence landing page 

### ISSUE THREAD

**Issue by bumi** [Coinsence/meta#37]
Once https://github.com/Coinsence/humhub-modules-custom-pages/pull/3 is deployed we can create custom HTML landing pages. @KarimChabrak had proposed a landing page content/design for the Coinsence humhub project in: https://github.com/Coinsence/meta/issues/2

we need to implement that page on coinsence.org

**Comment by craxrev** [comment]
So is Karim going to fill it by himself, or should I do it by my own?

**Comment by gdalyy** [comment]
I think that @KarimChabrak or any other non techie guy should do that, to see if that was easy to do or not .

**Comment by craxrev** [comment]
Ghaith, I think the state of the feature on time being is for techie guys, once the full CKEditor is implemented, we can test user interactions with it and how easy is perceived.

**Comment by craxrev** [comment]
But yeah if Karim can do it, he should be the one doing it :+1:

**Comment by bumi** [comment]
here is my comment on this: https://github.com/Coinsence/meta/issues/2#issuecomment-462964517 

my suggestion is: we design and develop a nice landing page for any space that will actively use coinsence. once we have more than 5 landing pages implemented we start with optimizing the editor.

**Comment by bumi** [comment]
oh and we don't develop that app for @KarimChabrak only :)

**Comment by craxrev** [comment]
so as @bumi suggested, I made a working [draft](http://dev.coinsence.org/index.php?r=custom_pages%2Fcontainer%2Fview&id=3&cguid=8ae128c1-2652-4b97-8904-691416819589) for the coinsence landing page on the dev platform so we can drop it later in production once the feature's deployed.
