### ISSUE TITLE
Define the process how to deploy new feature in the live network

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#38]
As developere team, we would like to deploy new features on the coinsence platform which is hosted by humhub.

**Comment by KarimChabrak** [comment]
@luke-     Can you let us know how we could deploy the new features on our  live network which is hosted by you?

**Comment by luke-** [comment]
@KarimChabrak Sorry I missed this issue. Do you still need input from me?

**Comment by KarimChabrak** [comment]
@luke-   we jointly solved this issue long times ago. Maybe you forgot.
