### ISSUE TITLE
Add a way to transfer coins from task account

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#39]
As responsible for a task, I would like to transfer coins from task account.    Even though i am the manager of the account, I can not see the transfer button.

**Comment by KarimChabrak** [comment]
Ok, at least i can make a transaction when i enter into the account

![image](https://user-images.githubusercontent.com/41925899/53188385-7fe59700-3605-11e9-87ff-897a2294c602.png)


![image](https://user-images.githubusercontent.com/41925899/53188399-8a079580-3605-11e9-8ab1-25bf217b5783.png)

**Comment by bumi** [comment]
so this can be closed?

**Comment by gdalyy** [comment]
Should I start with this issue ?

**Comment by bumi** [comment]
no. I thought this can be closed?
and we should only work on things that we had moved into the todo column: https://github.com/Coinsence/meta/projects/1

**Comment by KarimChabrak** [comment]
This issue will be solved by issue #28. So no need to work on it. We can close it.
