### ISSUE TITLE
Migrate from Rinkeby to Algorand

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#399]
You know

**Comment by gdalyy** [comment]
https://github.com/Coinsence/coinsence-monorepo

**Comment by KarimChabrak** [comment]
Test results 15.8.2022 and open issue:
- Each created account, gets per defaults 0.21 Algo. We need to check if this is necessary, as each new user would consume cost, even if he is not active. We need to consider increasing gas only when accounts receives assets or when spaces issue assets. 
- Still button "Ethereum" visible on space account overview.
- We should hide the private key retrieve button for all accounts, to ensure that users do not send out Algo from their accounts. 
- Remove "Create new coins" when space did issue already coins. SUPPLY CAN NOT BE INCREASED IN ALGORAND
- As supply can not be increased. We need to make user aware about this when he creates assets. When adding a new project to a campaign, we need to offer user the possibility to issue much more coins.

**Comment by KarimChabrak** [comment]
Tests 16.9.2022
- Creating space, does generate error message. Space is created, but account is not created.
- When initiating TND-COIN transaction from space, amount of available coins was wrong. Showing 5,000,000 instead of 4,999,990
-
