### ISSUE TITLE
Develop coin aragon app smart contracts

### ISSUE THREAD

**Issue by haythem96** [Coinsence/meta#41]

**Comment by haythem96** [comment]
The Coin aragon app will have acl permissions, that will inherit an ERC20 contract from openzeppelin package.

_ACL permissions:_

- ISSUE_TOKEN

- 
**All permissions will be created for the Coin app and will be granted to the space entity (this all done in the DAO newInstance)**

**Comment by bumi** [comment]
I think we have an issue with using openzeppelin... as those are not AragonApps and thus are not compatible with a proxy contract we can not easily inherit from one of the openzeppelin contracts.

**Comment by haythem96** [comment]
why not compatible with proxy contract ?

**Comment by bumi** [comment]
actually I think I am wrong... 
I thought they rely on the constructor calls (which is not called when behind a proxy). 
but the token contract does not have that: https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC20/ERC20.sol#L127

**Comment by haythem96** [comment]
for the issuing token, for now the space manager will get the ISSUE_ROLE to issue token for the space.
