### ISSUE TITLE
Introduction of new fields in add/edit forms for crowdfunding 

### ISSUE THREAD

**Issue by gdalyy** [Coinsence/meta#49]
As space admin, I shall be able to add the following information : 

- [x] Title 
- [x] Picture
- [x] Description
- [x] Deadline
- [x] needs  
- [x] commitment 
- [x] gallery

**Comment by gdalyy** [comment]
@KarimChabrak i need your confirmation about unchecked fields

**Comment by KarimChabrak** [comment]
Needs, commitment and gallery and any other info can be added by the admin if he has the freedom to edit his detailled project description.

**Comment by gdalyy** [comment]
I'm talking about common and necessary fields for each crowdfunding campaign ! Are we good with the list above ? 
 
Any other information that admin wants to add , he can add it to the campaign description or we can use a rich text editor like we did with the space landing page.

**Comment by gdalyy** [comment]
@KarimChabrak what do you think about using **humhub-gallery-module** to create crowdfunding galleries. See picture below.

PS : i'm not talkin about the main picture 

![FireShot Capture 182 - Test Space - Coinsence - coinsence](https://user-images.githubusercontent.com/13172404/54651593-dda9b980-4ab3-11e9-944d-d83adee94c78.png)

**Comment by KarimChabrak** [comment]
> @KarimChabrak what do you think about using **humhub-gallery-module** to create crowdfunding galleries. See picture below.
> 
> PS : i'm not talkin about the main picture
> 
> ![FireShot Capture 182 - Test Space - Coinsence - coinsence](https://user-images.githubusercontent.com/13172404/54651593-dda9b980-4ab3-11e9-944d-d83adee94c78.png)

If the potential investor has to go to the gallery to see the picture, I would rather leave the gallery feature away for the moment, so every crowd funding can have only a single desicated picture which is visible in the corwd-funding space.

If you use the gallery only to store the picture, but they are visible in the detailled crowd-funding description, then I am fully ok with this.

**Comment by gdalyy** [comment]
What i'm trying to say here, to create a crowdfunding campaign admin should : 
1- create a gallery for the campaign and upload pictures into the gallery 
2- create a camapgin , and in the last step of the form ,he links already created gallery to this campaign
3- all gallery pictures uploaded will be accessible in the crowdfunding overview (description) 

What do you think ?

**Comment by KarimChabrak** [comment]
Sounds good. But if it takes a lot of time to implement this, i would recommand to de-prioritize this for the moment. And add this as new issue for later iterations.
