### ISSUE TITLE
Crowd-funding image mismatch

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#56]
When uploading imageds in the crowd-funding description. 

- These images are then shown double  (within the description and as a gallery).
- The first image added to the text is used as crowd-funding main picture. 

The user shall be clearly have separate picture types:
- The main picture (at least the user shall be asked to upload this before starting the description).
- Gallery pictures.
- Pictures which are embedded in the description but not shown in gallery.

**Comment by KarimChabrak** [comment]
@gdalyy   as discussed.   We could first leave away the gallery.  So that user cxan only add the main picture and all other pictures can be added to text within "Needs & Commitments"

**Comment by gdalyy** [comment]
fixed
