### ISSUE TITLE
Allocating coins to certain jobs

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#7]
As project manager, I would like to be able to optionally allocate a certain budget to a task, to ensure that this budget is blocked for the task and to inform the task maker how much coins are reserved as a reward.

As community member without budget, i would like to enable community members to allocate some budget to a certain task.

As community, we need ways to collectively approve a certain task delivery and initiate a transaction to the account which has made the task.

As task maker, i would like to inform the task initiator to which account the coins shall be transferred.

**Comment by KarimChabrak** [comment]
"As community member without budget, i would like to enable community members to allocate some budget to a certain task"
I mean with this that task creator can add budget request to the task, and different user can send coins to this task.

**Comment by gdalyy** [comment]
Hi @KarimChabrak, i'm wondering about the workflow of the coins allocation: 

- space new account creation comes first then when creating a task we just link the according account and provide the account that coins will go to 
- when creating the task w choose the amount and which account this amount will go to and an acccount that belongs to the space is automatically created were coins will be blocked ? 
- when creating the task in the same popup we fill account parameters ( amount, account name, account manager ) and provide the account that coins will go to 

Which of these options is the best ? or there is an other manner to do this ?

**Comment by KarimChabrak** [comment]
1st issue (enable allocating budget to ask):
We creating a task AND clicking "allocate budget", an account with taks ID is created in the space and is associated to this task.
(Any user can then send coins to this task  account. This is done independent from the task module). 
The budget in the task account is also visible somewhere in the task description. 
   
2nd issue (setting payment account)
When allocating a task to a user (worker), this "assigned user" can set then in the task description the payment account. He can select whatever account he wants. 

3rd issue (concluding a task)
When task has been accomplished, the "responsible user" can simply click in the review process besides "accept" or "reject" also "accept and pay" or "reject and refund"

- "accept and pay" the task account content is transmitted to the "assigned user". 
- "reject and refund" coins are sent back to the accounts where they came from.

![image](https://user-images.githubusercontent.com/41925899/52507194-1fac2980-2bf1-11e9-8132-263b7afdfde4.png)

![image](https://user-images.githubusercontent.com/41925899/52507609-4dde3900-2bf2-11e9-91a8-6929a541263d.png)


I see this a the first simple flow we can build.  

We can introduce later much more other functionalities.

**Comment by gdalyy** [comment]
Thanks karim now the flow is clear, what about about dividing this issue into three more granular issues ?
Other question: when creating the task no fixed amount is provided ? 
So amount reached that exists in the account linked to the task when it's accomplished will be transferred to worker account or refund to accounts where it comes from.

**Comment by KarimChabrak** [comment]
We can devide this issue into more granularity.

Regarding your question: When creating a task no fixed amount is provides. This can be done manually by sending coins to the task account. Because, some times you create a task first collect feddback from potential worker, we you agree with one, you then assign a user and send the agreed coin amount to the task account. 

Yes, amount reached that exists in the account linked to the task when it's accomplished will be transferred to worker account or refund to accounts where it comes from.

**Comment by gdalyy** [comment]
Linking sub issues :

- [ ] #26 
- [ ] #27
- [ ] #28
