### ISSUE TITLE
Integrate smart contracts into humhub

### ISSUE THREAD

**Issue by haythem96** [Coinsence/meta#70]
In order issue coins on the etherum smart contracts we need to integrate the humhub application with the smart contracts.
integration means that humhub needs to initiate contract calls. 

@bumi recommendation: write a wrapper around the ethereum smart contracts that expose a rest interface that can be called from humhub

**Comment by bumi** [comment]
which events trigger which contract call? 

### space creation => DAO initialization. / coinsencekit#newInstance
* owned by the user who creates the space
* if the user does not have a wallet yet, we need to create one => how do we fund it to pay for gas fees? 

###  coin issuance => token minting 
* currently only possible to etherum accounts/wallets - is that a limitation on humhub?

**Comment by haythem96** [comment]
###accept member request to join space => spaceApp#addMembers()
* need to be called by the space owner to add a member

###space member leave => spaceApp#leaveSpace
* can be called by a space member to leave a space

**Comment by haythem96** [comment]
for the member request to join space, @gdalyy maybe need to pass member address as additional info in the join request (to save it in the request table, request object or whatever... the way humhub currently work..he knows better XD ) so that later when space owner accept that request, humhub can call the contract function through the API (to pass to the API the member address to be added)

**Comment by gdalyy** [comment]
from where i can get the correct member address ? through an API call ? so that i can store it in MYSQLdb and then use it whenever there is a need !
