### ISSUE TITLE
Create Ethereum wallet for humhub accounts

### ISSUE THREAD

**Issue by bumi** [Coinsence/meta#74]
In the first step we store the ethereum wallets for the accounts. 

To make sure every account has an ethereum account/wallet and enough funds we need to initialize a new wallet once an account is created.

This does not scale and costs us ETH to fund the accounts, but that's good for the first step and we don't have so many users in the first step

- [x] HTTP wrapper endpoint

- [ ] humhub HTTP call

related: #72

**Comment by bumi** [comment]
we can do the wallet management in the wrapper HTTP app. 
which means we can expose an interface to create wallet: 
something like: 
`POST /wallets` with params: `userId=humhub userid`

**Comment by bumi** [comment]
maybe we can show the user the mnemonic codes on request or during setup in their profile?

**Comment by haythem96** [comment]
yeah good idea... at least the user have something related to his wallet for now.
