### ISSUE TITLE
Join ethereum DAO when a member joins a space 

### ISSUE THREAD

**Issue by bumi** [Coinsence/meta#75]
The etherum contracts store a list of accounts that participate in a space. 
When a user joins a space we need to do a call to the wrapper HTTP interface. 

### ToDo:
- [x] HTTP API
- [x] humhub integration 

### Questions:
*  when has a user joined a space in humhub? is there a confirmation from the space owner required?
* can we store some information (ethereum transaction ID) about the call in a "membership" table on humhub?

**Comment by haythem96** [comment]
* I think space owner need to accept user request to join space

**Comment by bumi** [comment]
but do we need to do that in the contract? or can we simply add the user to the space once the membership is confirmed in humhub?

**Comment by haythem96** [comment]
yup that's what we will do, there is no join request in the contract... we keep everything as it is now, one the membership confirmed by the space manager on humhub we add the user on the contract.
