### ISSUE TITLE
Ethereum integration for coin issuance 

### ISSUE THREAD

**Issue by bumi** [Coinsence/meta#76]
When a ~~user~~ space manager/owner issues new coins we need to issue those on the ethereum smart contract. 

- [x] HTTP wrapper endpoint

- [x] humhub HTTP call

**Comment by gdalyy** [comment]
Users can't issue coins , only spaces can issue their coins

**Comment by bumi** [comment]
which is triggered by some user :) 
in the first step we probably only have user accounts on ethereum. Or @haythem96 should we also create a wallet for the space itself?

**Comment by haythem96** [comment]
mm I don't think so... let's keep it this way for now
Later we can modify the issuing coin process (by voting from all space members and maybe using a vault or a multisig wallet for the coin issuing) but in all cases, an user need to trigger the action, a space can not by itself create/issue a token...

**Comment by gdalyy** [comment]
From humhub side when space administrator issue coins , then an account [ISSUES as type] with space id is created not with user id , i think we should do the same thing on blockchain level ! spaces must have their own wallets .

**Comment by haythem96** [comment]
I think at some point we need to modify humhub even if we want to modify the minimum code there... at the end it wasn't built for Coinsence.

**Comment by gdalyy** [comment]
No, **xcoin** module is built for coinsence , it's true that a space account is managed by a user, but it belongs to the space itself not to a moderator user, so i think it's better that same as users , spaces can have their own wallets

**Comment by bumi** [comment]
coins are issued for one recipient - afaik in coinsence right now stores coins associated with an account which is managed by one or more users, correct? 
in the smart contracts coins are owned by an "account" - which is a wallet or a smart contract (mutli-sig vault, voting contract, etc.) 
so war we only have wallets. 

we could think about creating a wallet for every "account" in humhub?

**Comment by gdalyy** [comment]
Every account in coinsence is managed by one and only one user.
I think it's better to create a wallet for every account.

**Comment by bumi** [comment]
ok, so we will create an ethereum wallet for every account.
