### ISSUE TITLE
Disable Crowdfunding creation when asset is missing

### ISSUE THREAD

**Issue by gdalyy** [Coinsence/meta#90]

**Comment by KarimChabrak** [comment]
Dear @gdalyy 

do you mean here, handle the issue of crowdinvesting when asset is missing? 

![image](https://user-images.githubusercontent.com/41925899/58311167-a4216180-7e08-11e9-84ef-08d47e5ede0a.png)

If yes, I propose to show the user only accounts which contain the requested coins, if he has not account containing the coins, then we show the message "You have no accounts with the requested coins"

![image](https://user-images.githubusercontent.com/41925899/58310963-307f5480-7e08-11e9-9df0-c27c72a09b63.png)

**Comment by gdalyy** [comment]
No , i mean disable crowdfunding creating when there is no issued coins for the space in question
