### ISSUE TITLE
Show in crowdfunding only accounts with contain requested coins

### ISSUE THREAD

**Issue by KarimChabrak** [Coinsence/meta#95]
As user i have to select when willing to invest in crowdfunding from multiple accounts, also those which are not relevant because they do not contain requested coin. 

![image](https://user-images.githubusercontent.com/41925899/58358133-df11ac80-7e7d-11e9-95e2-b887c55735ad.png)

If i request a wrong account and put a high amount, then iget an unclear message

![image](https://user-images.githubusercontent.com/41925899/58358142-f486d680-7e7d-11e9-94a0-012b9d8bfd73.png)

**I propose to show the user only accounts which contain the requested coins,

- if he has no account containing the coins, then we show the message "You have no accounts with the requested coins".

- When user selects an account containing the requested assets, in the next step we show him the maximum amount he can invest. =Max (balance of selected user invest account , The current balance of the funding account / rate)**

**Comment by gdalyy** [comment]
Done within the crowdfunding optimization
