### ISSUE TITLE
Disable transferring back coin to ISSUE account 

### ISSUE THREAD

**Issue by gdalyy** [Coinsence/meta#99]
Since `ISSUE account` is the only account that does not have a wallet on blockchain , we should not allow space administrators to transfer back coin to `ISSUE account` otherwise transfer function will not work. 

Not triggering ether transfer function from humhub side when detecting that the receiver account is the `ISSUE account` is feasible but in this case we'll have wrong balances on blockchain that why we should avoid such type of transaction.

**Comment by KarimChabrak** [comment]
@gdalyy     This transaction to issue account should normally trigger  COIN burning in Blockchain. 

But as this is at the moment not important, i propose to not show the issue account in the list shown below.

![image](https://user-images.githubusercontent.com/41925899/59147766-dd102780-89ff-11e9-95a2-3836654a3ad5.png)

Normally, we should remove the issue account completely and just display somewhere the total issued space coins.

**Comment by gdalyy** [comment]
I asked for this since we're not migrating issue accounts on the blockchain.

> Normally, we should remove the issue account completely and just display somewhere the total issued space coins. :+1:  :+1:

**Comment by KarimChabrak** [comment]
Of you agree @gdalyy , you are welcome to remove issue account
